### PR TITLE
Add user unit tests

### PR DESCRIPTION
**Pull request by snesbittsea**
Unit tests for profile::users::static

Tschuss!

-steve

### CODE REVIEW

**Comment by tuxmea** [comment]
@snesbittsea some code checks are failing. can you please look into codacy results? https://www.codacy.com/app/alvagante/control-repo/pullRequest?prid=554987

**Comment by snesbittsea** [comment]
I'll take a look at it. I'm not sure to what extent the warnings apply to
the rspec DSL. If you have an example of a compliant rspec-puppet test that
would be most helpful.

-steve

**Comment by alvagante** [comment]
Going to merge the PR anyway, the style checks of Codacity on different languages is somehow picky at times (even if relevant language cleanups on the committed code will still be very welcomed)

**Comment by alvagante** [comment]
Oops, in the various merge requests  I squashed your commits, Stephen, so they don't appear in the git history with your name. Sorry!

**Comment by snesbittsea** [comment]
No problem on the squash.

Regards, Codacity I'll definitely cleanup the indicated formatting issues. The Ruby specific issues regarding hashes, complexity don't appear to be relevant (although I am not a Ruby expert).

Would it be worth your time to take one of the unit test cases and make the changes necessary so that it could be used as an standard?

**Comment by alvagante** [comment]
Hei Steve,
thanks for the support.
You can ignore the main_spec.rb.erb in the skeleton.
The ability to load facts from fixtures/facts/spec.yaml should be added to erb templates, if possible.

At the moment we do acceptance tests only via tp test and collateral scripting, but in the spirit of the control-repo ("more is better than less") we definitively would accept PR with "real" acceptance tests for profile classes.
+1 for nodesets based on docker.

**Pull request merged**
